// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import java.io.InputStream;
import java.util.List;
import java.util.HashMap;
import java.math.BigDecimal;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import myfirstmodule.proxies.Customer;
import myfirstmodule.proxies.OrderHeader;
import myfirstmodule.proxies.OrderLineItem;
import myfirstmodule.proxies.Product;

public class JA_ImportXlsxToEntities extends UserAction<java.lang.Boolean>
{
	/** @deprecated use Parameter.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Parameter;
	private final myfirstmodule.proxies.ImporterFile Parameter;

	public JA_ImportXlsxToEntities(
		IContext context,
		IMendixObject _parameter
	)
	{
		super(context);
		this.__Parameter = _parameter;
		this.Parameter = _parameter == null ? null : myfirstmodule.proxies.ImporterFile.initialize(getContext(), _parameter);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		if (this.Parameter == null)
			return false;

		try {
			InputStream inputStream = Core.getFileDocumentContent(context, this.Parameter.getMendixObject());

			try (Workbook workbook = WorkbookFactory.create(inputStream)) {
				Sheet sheet = workbook.getSheetAt(0);

				for (int i = 1; i <= sheet.getLastRowNum(); i++) {
					Row row = sheet.getRow(i);
					if (row == null)
						continue;

					// 1. Column Mapping (A=0, B=1, C=2, D=3, E=4, F=5, G=6, H=7, I=8, J=9, K=10,
					// L=11, M=12, N=13, O=14, P=15, Q=16, R=17, S=18, T=19)
					String lineItemIDVal = getCellValue(row.getCell(0));
					String orderIDVal = getCellValue(row.getCell(1));
					String custIDVal = getCellValue(row.getCell(2));
					String prodIDVal = getCellValue(row.getCell(3));

					// 2. Process CUSTOMER
					IMendixObject customerObj = retrieveSingleObject(context, Customer.entityName, "CustomerID",
							custIDVal);
					Customer customer = (customerObj == null) ? new Customer(context)
							: Customer.initialize(context, customerObj);
					customer.setCustomerID(custIDVal);
					customer.setRegion(getCellValue(row.getCell(8)));

					// 3. Process ORDER HEADER
					IMendixObject headerObj = retrieveSingleObject(context, OrderHeader.entityName, "OrderNumber",
							orderIDVal);
					OrderHeader header = (headerObj == null) ? new OrderHeader(context)
							: OrderHeader.initialize(context, headerObj);
					header.setOrderNumber(orderIDVal);
					header.setWarehouseID(getCellValue(row.getCell(4)));
					header.setOrderDate(safeGetDate(row.getCell(5)));
					header.setShipmentDate(safeGetDate(row.getCell(6)));
					header.setStatus(getCellValue(row.getCell(7)));
					header.setTrackingNumber(getCellValue(row.getCell(19)));
					header.setCarrier(getCellValue(row.getCell(18)));
					header.setOrderHeader_Customer(customer);

					// 4. Process PRODUCT
					IMendixObject productObj = retrieveSingleObject(context, Product.entityName, "ProductID",
							prodIDVal);
					Product product = (productObj == null) ? new Product(context)
							: Product.initialize(context, productObj);
					product.setProductID(prodIDVal);
					product.setUnitPrice(safeGetDecimal(row.getCell(10)));

					// 5. Process LINE ITEM
					OrderLineItem lineItem = new OrderLineItem(context);
					lineItem.setLineItemID(lineItemIDVal);
					lineItem.setUnitPrice(safeGetDecimal(row.getCell(10)));
					lineItem.setQuantity(safeGetDecimal(row.getCell(11)).intValue());
					lineItem.setDiscount(safeGetDecimal(row.getCell(12)));
					lineItem.setTax(safeGetDecimal(row.getCell(13)));
					lineItem.setNetTotal(safeGetDecimal(row.getCell(14)));
					lineItem.setGrossTotal(safeGetDecimal(row.getCell(15)));
					lineItem.setWeight(safeGetDecimal(row.getCell(16)));
					lineItem.setVolume(safeGetDecimal(row.getCell(17)));

					lineItem.setOrderLineItem_OrderHeader(header);
					lineItem.setOrderLineItem_Product(product);

					// 6. Commit All
					Core.commit(context, customer.getMendixObject());
					Core.commit(context, header.getMendixObject());
					Core.commit(context, product.getMendixObject());
					Core.commit(context, lineItem.getMendixObject());
				}
			}
			return true; // SUCCESS!
		} catch (Exception e) {
			Core.getLogger("ExcelImport").error("Import failed: " + e.getMessage());
			return false; // FAILED!
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ImportXlsxToEntities";
	}

	// BEGIN EXTRA CODE
	private IMendixObject retrieveSingleObject(IContext context, String entityName, String attr, String value)
			throws CoreException {
		if (value == null || value.isEmpty())
			return null;
		String xpath = "//" + entityName + "[" + attr + "='" + value + "']";
		List<IMendixObject> results = Core.retrieveXPathQuery(context, xpath, 1, 0, new HashMap<String, String>());
		return results.isEmpty() ? null : results.get(0);
	}

	private BigDecimal safeGetDecimal(Cell cell) {
		if (cell == null)
			return BigDecimal.ZERO;
		try {
			if (cell.getCellType() == CellType.NUMERIC)
				return BigDecimal.valueOf(cell.getNumericCellValue());
			if (cell.getCellType() == CellType.STRING) {
				String val = cell.getStringCellValue().replaceAll("[^0-9.]", "");
				return val.isEmpty() ? BigDecimal.ZERO : new BigDecimal(val);
			}
		} catch (Exception e) {
			return BigDecimal.ZERO;
		}
		return BigDecimal.ZERO;
	}

	private java.util.Date safeGetDate(Cell cell) {
		if (cell != null && cell.getCellType() == CellType.NUMERIC && DateUtil.isCellDateFormatted(cell)) {
			return cell.getDateCellValue();
		}
		return null;
	}

	private String getCellValue(Cell cell) {
		if (cell == null)
			return "";
		if (cell.getCellType() == CellType.STRING)
			return cell.getStringCellValue();
		if (cell.getCellType() == CellType.NUMERIC)
			return String.format("%.0f", cell.getNumericCellValue());
		return "";
	}
	// END EXTRA CODE
}
